/*****************************************************************************
//	RTSP SDK Base Classes
//
//	Base Definitions Header
//
//	description:
//		contains basic definitions and preprocessor conditions
//
//	revision of last commit:
//		$Rev$
//	author of last commit:
//		$Author$
//	date of last commit:
//		$Date$
//
//	created by Argenet {argenet@sibears.org}
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//
******************************************************************************/


#ifndef __RTSP_SDK__H__
#define __RTSP_SDK__H__

//
// Ensure that RTSP_SDK_DLL is default unless RTSP_SDK_STATIC is defined
//
#if defined(_WIN32) && defined(_DLL)
	#if !defined(RTSP_SDK_DLL) && !defined(RTSP_SDK_STATIC)
		#define RTSP_SDK_DLL
	#endif
#endif

//
// The following block is the standard way of creating macros which make exporting
// from a DLL simpler. All files within this DLL are compiled with the RTSP_SDK_EXPORTS
// symbol defined on the command line. this symbol should not be defined on any project
// that uses this DLL. This way any other project whose source files include this file see
// RTSP_SDK_API functions as being imported from a DLL, wheras this DLL sees symbols
// defined with this macro as being exported.
//
#if defined(_WIN32) && defined(RTSP_SDK_DLL)
	#if defined(RTSP_SDK_EXPORTS)
		#define RTSP_SDK_API __declspec(dllexport)
	#else
		#define RTSP_SDK_API __declspec(dllimport)
	#endif
#endif


#if !defined(RTSP_SDK_API)
	#define RTSP_SDK_API
#endif


//
// Automatically link RTSP SDK library.
//
#if defined(_MSC_VER)
	#if !defined(POCO_NO_AUTOMATIC_LIBS) && !defined(RTSP_SDK_EXPORTS)
		#if defined(RTSP_SDK_DLL)
			#if defined(_DEBUG)
				#pragma comment(lib, "rtsp_sdkd.lib")
			#else
				#pragma comment(lib, "rtsp_sdk.lib")
			#endif
/*
		#else
			#if defined(_DEBUG)
				#pragma comment(lib, "PocoNetmtd.lib")
			#else
				#pragma comment(lib, "PocoNetmt.lib")
			#endif
			*/
		#endif
	#endif
#endif


#endif // __RTSP_SDK__H__
