/*****************************************************************************
//	SDP Parser Classes
//
//	Time Description Class
//
//	revision of last commit:
//		$Rev$
//	author of last commit:
//		$Author$
//	date of last commit:
//		$Date$
//
//	created by Argenet {argenet@sibears.org}
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//
******************************************************************************/

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
//	Includes
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#include "Poco/SDP/TimeDescription.h"
#include "Poco/SDP/FieldFactory.h"

namespace Poco {
namespace SDP {

using std::string;

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
//	TimeDescription class implementation
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
//	Public methods
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

TimeDescription :: TimeDescription(const std::string & timeDescription)
{
	StringVec lines = split(timeDescription, "\r\n");

	Field * pField = FieldFactory::CreateInstance(lines[0]);
	_timeField = * (dynamic_cast<TimeField *>(pField));
	FieldFactory::DestroyInstance(pField);
	for(size_t i = 1 ; i < lines.size() ; ++i)
	{
		if(lines[i].size() > 0)
		{
			Field * pField = FieldFactory::CreateInstance(lines[i]);
			_repetitions.push_back(* (dynamic_cast<TimeRepetitionField *>(pField)));
			FieldFactory::DestroyInstance(pField);			
		}
	}
}

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

TimeDescription :: TimeDescription(const TimeField & timeField)
	: _timeField(timeField)
{
}

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

TimeDescription :: TimeDescription(const TimeField & timeField,
					const TimeRepetitionVec & repetitions)
	: _timeField(timeField)
	, _repetitions(repetitions)
{
}

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

TimeDescription :: TimeDescription(const TimeDescription & timeDescription)
	: _timeField(timeDescription._timeField)
	, _repetitions(timeDescription._repetitions)
{
}

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

TimeDescription & TimeDescription :: operator=(const TimeDescription & timeDescription)
{
	if(&timeDescription != this)
	{
		_timeField = timeDescription._timeField;
		_repetitions = timeDescription._repetitions;
	}

	return *this;
}

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

inline TimeField TimeDescription :: getTimeField() const
{
	return _timeField;
}

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

inline TimeRepetitionVec TimeDescription :: getRepetitions() const
{
	return _repetitions;
}

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

inline std::string TimeDescription :: toString() const
{
	string str = "t=" + _timeField.toString() + "\r\n";
	for(size_t i = 0 ; i < _repetitions.size() ; ++i)
	{
		str += _repetitions[i].toString();
	}

	return str;
}

} //	namespace SDP
} //	namespace Poco
