/*****************************************************************************
//	RTSP SDK Base Classes
//
//	RTSP Header Stream classes
//
//	revision of last commit:
//		$Rev$
//	author of last commit:
//		$Author$
//	date of last commit:
//		$Date$
//
//	created by Argenet {argenet@sibears.org}
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//
******************************************************************************/

#include "Poco/RTSP/RTSPHeaderStream.h"
#include "Poco/RTSP/RTSPSession.h"

namespace Poco {
namespace RTSP {

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
//	RTSPHeaderStreamBuf class implementation
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

RTSPHeaderStreamBuf::RTSPHeaderStreamBuf(RTSPSession& session, openmode mode):
	RTSPBasicStreamBuf(HTTPBufferAllocator::BUFFER_SIZE, mode),
	_session(session),
	_end(false)
{
}


RTSPHeaderStreamBuf::~RTSPHeaderStreamBuf()
{
}


int RTSPHeaderStreamBuf::readFromDevice(char* buffer, std::streamsize length)
{
	// read line-by-line; an empty line denotes the end of the headers.
	static const int eof = std::char_traits<char>::eof();

	if (_end) return 0;

	int n = 0;
	int ch = _session.get();
	while (ch != eof && ch != '\n' && n < length - 1)
	{
		*buffer++ = (char) ch; ++n;
		ch = _session.get();
	}
	if (ch != eof)
	{
		*buffer++ = (char) ch; ++n;
		if (n == 2) _end = true;
	}
	return n;
}


int RTSPHeaderStreamBuf::writeToDevice(const char* buffer, std::streamsize length)
{
	return _session.write(buffer, length);
}


//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
//	RTSPHeaderIOS class implementation
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


RTSPHeaderIOS::RTSPHeaderIOS(RTSPSession& session, RTSPHeaderStreamBuf::openmode mode):
	_buf(session, mode)
{
	poco_ios_init(&_buf);
}


RTSPHeaderIOS::~RTSPHeaderIOS()
{
	try
	{
		_buf.sync();
	}
	catch (...)
	{
	}
}


RTSPHeaderStreamBuf* RTSPHeaderIOS::rdbuf()
{
	return &_buf;
}


//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
//	RTSPHeaderInputStream class implementation
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Poco::MemoryPool RTSPHeaderInputStream::_pool(sizeof(RTSPHeaderInputStream));


RTSPHeaderInputStream::RTSPHeaderInputStream(RTSPSession& session):
	RTSPHeaderIOS(session, std::ios::in),
	std::istream(&_buf)
{
}


RTSPHeaderInputStream::~RTSPHeaderInputStream()
{
}


void* RTSPHeaderInputStream::operator new(std::size_t size)
{
	return _pool.get();
}


void RTSPHeaderInputStream::operator delete(void* ptr)
{
	_pool.release(ptr);
}


//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
//	RTSPHeaderOutputStream class implementation
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Poco::MemoryPool RTSPHeaderOutputStream::_pool(sizeof(RTSPHeaderOutputStream));


RTSPHeaderOutputStream::RTSPHeaderOutputStream(RTSPSession& session):
	RTSPHeaderIOS(session, std::ios::out),
	std::ostream(&_buf)
{
}


RTSPHeaderOutputStream::~RTSPHeaderOutputStream()
{
}


void* RTSPHeaderOutputStream::operator new(std::size_t size)
{
	return _pool.get();
}


void RTSPHeaderOutputStream::operator delete(void* ptr)
{
	_pool.release(ptr);
}


} //	namespace RTSP
} //	namespace Poco
