/*****************************************************************************
//	SDP Parser Classes
//
//	Attribute Field Class
//
//	description:
//		represents SDP description attribute field
//
//	revision of last commit:
//		$Rev$
//	author of last commit:
//		$Author$
//	date of last commit:
//		$Date$
//
//	created by Argenet {argenet@sibears.org}
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//
******************************************************************************/

#ifndef __ATTRIBUTE_FIELD__H__
#define __ATTRIBUTE_FIELD__H__

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
//	Includes
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#include "sdp_parser.h"

#include "common.h"
#include "Field.h"

namespace SDP {

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
//	AttributeField class
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

class SDP_PARSER_API AttributeField : public Field
	/// An Attribute represents the a= fields contained in either a MediaDescription or
	/// SessionDescription. They can be either an identity or a name-value pair.
	/// 
	/// For example:
	/// 
	///   a=recvonly  //Just the presence of this atttribute implies state. 
	///   a=rtpmap:0 PCMU/8000 //Identifies the media format 0 as being PCMU/8000.
	/// 
	/// The value must be preceded by the : character if present.
{
public:

	AttributeField();
	/// Creates an empty AttributeField.

	AttributeField(const std::string & value);
	/// Creates a new AttributeField according to the specified value string.

	AttributeField(const std::string & name, const std::string & attrValue);
	/// Creates a new AttributeField according to the specified name or identity 
	/// of the attribute and the value of the attribute (should be left empty if
	/// the attribute is recognized by identity.

	AttributeField(const AttributeField & attributeField);
	/// Creates a copy of specified AttributeField object.

	AttributeField & operator=(const AttributeField & attributeField);
	/// Copies the specified AttributeField object.

	std::string getName() const;
	/// Gets the name of the attribute.

	std::string getAttributeValue() const;
	/// Gets the value of this attribute.

	bool hasValue() const;
	/// Returns whether or not this attribute has a value.

	virtual std::string getValue() const;
	/// Gets the value portion of this field.
	
private:

	std::string			_name;
	std::string			_attributeValue;

};

} //	namespace SDP

#endif	//	__ATTRIBUTE_FIELD__H__

