/*****************************************************************************
//	SDP Parser Classes
//
//	Bandwidth Modifiers
//
//	description:
//		represents the bandwidth modifiers defined in RFC 2327
//
//	revision of last commit:
//		$Rev$
//	author of last commit:
//		$Author$
//	date of last commit:
//		$Date$
//
//	created by Argenet {argenet@sibears.org}
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//
******************************************************************************/

#ifndef __BANDWIDTH_MODIFIERS__H__
#define __BANDWIDTH_MODIFIERS__H__

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
//	Includes
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#include "sdp_parser.h"
#include "common.h"

namespace SDP {

typedef struct SDP_PARSER_API _BandwidthModifiers
/// A structure of listed bandwidth modifiers.
{
	static const std::string ConferenceTotal;
	/// From RFC 2327:
	/// Conference Total: An implicit maximum bandwidth is associated with
	/// each TTL on the Mbone or within a particular multicast administrative 
	/// scope region (the Mbone bandwidth vs. TTL limits are given in the 
	/// MBone FAQ). If the bandwidth of a session or media in a session is 
	/// different from the bandwidth implicit from the scope, a `b=CT:...' 
	/// line should be supplied for the session giving the proposed upper 
	/// limit to the bandwidth used. The primary purpose of this is to give 
	/// an approximate idea as to whether two or more conferences can co-exist 
	/// simultaneously.

	static const std::string ApplicationSpecificMaximum;
	/// From RFC 2327:
	/// Application-Specific Maximum: The bandwidth is interpreted to be
	/// application-specific, i.e., will be the application's concept of
	/// maximum bandwidth.  Normally this will coincide with what is set on
	/// the application's "maximum bandwidth" control if applicable.

} BandwidthModifiers;

} //	namespace SDP

#endif	//	__BANDWIDTH_MODIFIERS__H__

