/*****************************************************************************
//	SDP Parser Classes
//
//	E-Mail Field Class
//
//	description:
//		represents SDP description e-mail field
//
//	revision of last commit:
//		$Rev$
//	author of last commit:
//		$Author$
//	date of last commit:
//		$Date$
//
//	created by Argenet {argenet@sibears.org}
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//
******************************************************************************/

#ifndef __E_MAIL_FIELD__H__
#define __E_MAIL_FIELD__H__

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
//	Includes
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#include "sdp_parser.h"
#include "common.h"
#include "Field.h"

namespace SDP {

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
//	EMailField class
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

class SDP_PARSER_API EMailField : public Field
	/// An E-Mail represents an e= field contained within a SessionDescription.
{
public:

	EMailField();
	/// Creates an empty EMailField.

	EMailField(const std::string & value);
	/// Creates a new EMailField according to the specified value string.

	EMailField(const std::string & userName, const std::string & host);
	/// Creates a new EMailField with specified username and host.

	EMailField(const std::string & userName,
			   const std::string & host,
			   const std::string & displayName);
	/// Creates a new EMailField with specified username, host and displayname.

	EMailField(const EMailField & emailField);
	/// Creates a copy of specified EMailField object.

	EMailField & operator=(const EMailField & emailField);
	/// Copies the specified EMailField object.

	std::string getUserName() const;
	/// Gets the username portion of this email address.

	std::string getDisplayName() const;
	/// Gets the display name.

	std::string getHost() const;
	/// Gets the host.

	std::string getEmailAddress() const;
	/// Gets the full string representation of the email address: username@host (displayname).

	virtual std::string getValue() const;
	/// Returns the field value.

private:

	void Init();
	/// Initializes internal object fields.

	std::string			_userName;
	std::string			_displayName;
	std::string			_host;

};

} //	namespace SDP

#endif	//	__E_MAIL_FIELD__H__

