/*****************************************************************************
//	SDP Parser Classes
//
//	Key Field Class
//
//	description:
//		represents SDP description key field
//
//	revision of last commit:
//		$Rev$
//	author of last commit:
//		$Author$
//	date of last commit:
//		$Date$
//
//	created by Argenet {argenet@sibears.org}
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//
******************************************************************************/

#ifndef __KEY_FIELD__H__
#define __KEY_FIELD__H__

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
//	Includes
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#include "Poco/SDP/Common.h"
#include "Poco/SDP/Field.h"

namespace Poco {
namespace SDP {

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
//	KeyField class
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

class SDP_API KeyField : public Field
	/// A Key represents the k= field contained within either a MediaDescription
	/// or a SessionDescription.
{
public:

	KeyField();
	/// Creates an empty KeyField.

	KeyField(const std::string & value);
	/// Creates a new KeyField according to the specified value string.

	KeyField(const std::string & method, const std::string & key);
	/// Creates a new KeyField with specified method and key.

	KeyField(const KeyField & keyField);
	/// Creates a copy of specified KeyField object.

	KeyField & operator=(const KeyField & keyField);
	/// Copies the specified KeyField object.

	std::string getMethod() const;
	/// Gets the method of encryption to use. See EncryptionMethods

	std::string getKey() const;
	/// Gets the encryption key, if there is one.

	bool hasKey() const;
	/// Determines whether or not a key is present.
	
private:

	void Init();
	/// Initializes internal object fields.

	std::string				_method;
	std::string				_key;

};

} //	namespace SDP
} //	namespace Poco

#endif	//	__KEY_FIELD__H__

