/*****************************************************************************
//	SDP Parser Classes
//
//	Time Description Class
//
//	description:
//		represents time description
//
//	revision of last commit:
//		$Rev$
//	author of last commit:
//		$Author$
//	date of last commit:
//		$Date$
//
//	created by Argenet {argenet@sibears.org}
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//
******************************************************************************/

#ifndef __TIME_DESCRIPTION__H__
#define __TIME_DESCRIPTION__H__

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
//	Includes
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#include "Poco/SDP/Common.h"
#include "Poco/SDP/TimeField.h"
#include "Poco/SDP/TimeRepetitionField.h"

namespace Poco {
namespace SDP {

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
//	Definitions and macroses
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

typedef std::vector<TimeRepetitionField> TimeRepetitionVec;

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
//	TimeDescription class
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

class SDP_API TimeDescription
    /// This class describes a time description. A session description may have one or more
    /// time descriptions.
{
public:

	TimeDescription(const std::string & timeDescription);
	/// Creates a new TimeDescription from the string representation
	/// of an existing TimeDescription.

	TimeDescription(const TimeField & timeField);
	/// Creates a new TimeDescription with the specified time field.

	TimeDescription(const TimeField & timeField,
					const TimeRepetitionVec & repetitions);
	/// Creates a new TimeDescription with the specified time field and
	/// the TimeRepetitionFields.

	TimeDescription(const TimeDescription & timeDescription);
	/// Creates a copy of specified TimeDescription object.

	TimeDescription & operator=(const TimeDescription & timeDescription);
	/// Copies the specified TimeDescription object.

	TimeField getTimeField() const;
	/// Gets the TimeField.

	TimeRepetitionVec getRepetitions() const;
	/// Gets or sets the times to repeat this session, if at all. Leave null if the
	/// session is not to be repeated.

	std::string toString() const;
	/// Converts TimeDescription to its string representation.

private:

	TimeField				_timeField;
	TimeRepetitionVec		_repetitions;
};

} //	namespace SDP
} //	namespace Poco

#endif	//	__TIME_DESCRIPTION__H__

